import {
  FooterNavigationType,
  LocationSliderType,
  LocationType,
  mapBackendStructure,
} from "@/types";

export const locationsSlider: LocationSliderType[] = [
  { label: "Ikorodu Lagos", imgURL: "/assets/images/ikorodu.png" },
  { label: "Abuja", imgURL: "/assets/images/abuja.png" },
  { label: "Port Harcourt", imgURL: "/assets/images/ph.png" },
  { label: "Ibadan, Oyo", imgURL: "/assets/images/ibadan.png" },
  { label: "Kano", imgURL: "/assets/images/kano.png" },
];

export const popularEvents: LocationType[] = [
  {
    label: "Donating Blood Festival",
    slug: "donating-blood-festival",
    time: "12.12.22",
    imgURL: "/assets/images/cinema.png",
    location:
      "Corporate Headquarters, Plot 1551, Apo Resettlement Zone E, Federal Capital Teritory",
    number: "+234 905 932 3873",
    category: "Charity Event",
    serviceFees: "Free",
    btnName: "Register",
    rateNumber: 4,
    rate: 20,
    close: "Closed",
    tags: ["Mexican", "Latin", "Grill"],
  },
  {
    label: "Chipotle Mexican Grill",
    slug: "chipotle-mexican-grill",
    open: "Open",
    openTime: "7:00 AM - 8:00 PM",
    imgURL: "/assets/images/chipotle.png",
    location: "Abiola Okeke, Medina estate, Gbagada, Lagos",
    locationestate: "Gbagada, Lagos",
    number: "+234 905 932 3873",
    tags: ["Mexican", "Latin", "Grill"],
    rateNumber: 4,
    category: "Fast Food",
    rate: 20,
  },
  {
    label: "Shoes by Becky",
    slug: "shoes-by-becky",
    openTime: "7:00 AM - 8:00 PM",
    imgURL: "/assets/images/shoe_business.png",
    location: "Abiola Okeke, Medina estate, Gbagada, Lagos",
    number: "+234 905 932 3873",
    category: "Shoes Store",
    open: "Open",
    website: "https://www.getprospa.com/webstore/shoesbybecky",
    tags: ["Shoe Store", "Cloth Store", "Clothes Customization"],
    rateNumber: 4,
    rate: 15,
  },
  {
    imgURL: "/assets/images/benz.png",
    label: "Grey BMW M5",
    slug: "grey-bmw-m5",
    category: "Cars",
    location: "Lagos, Nigeria",
    serviceFees: "12,640,500",
    number: "+234 905 932 3873",
    btnName: "Contact Buyer",
    close: "Closed",
    rate: 15,
    rateNumber: 1,
    tags: ["Shoe Store", "Cloth Store", "Clothes Customization"],
  },
  {
    label: "House Cleaning",
    slug: "house-cleaning",
    imgURL: "/assets/images/cleaning.png",
    category: "House Service",
    rate: 20,
    rateNumber: 3,
    serviceFees: "1,500 - 5,900",
    location: "Lagos, Nigeria",
    number: "+234 905 932 3873",
    organization: "Lange & Grant Commodities Limited",
    close: "Closed",
    tags: ["Shoe Store", "Cloth Store", "Clothes Customization"],
  },
];

export const popularFoodAndDrinks: LocationType[] = [
  {
    label: "Chipotle Mexican Grill",
    slug: "chipotle-mexican-grill",
    open: "Open",
    openTime: "7:00 AM - 8:00 PM",
    imgURL: "/assets/images/chipotle.png",
    location: "Abiola Okeke, Medina estate, Gbagada, Lagos",
    locationestate: "Gbagada, Lagos",
    number: "+234 905 932 3873",
    tags: ["Mexican", "Latin", "Grill"],
    rateNumber: 4,
    category: "Fast Food",
    rate: 20,
  },
  {
    label: "Boca Mexicana",
    slug: "boca-mexicana",
    open: "Open",
    openTime: "7:00 AM - 8:00 PM",
    imgURL: "/assets/images/pizza.png",
    location: "Suite 201, Block A2, 3 201 Simpson St, Lagos Island, Lagos",
    locationestate: "Gbagada, Lagos",
    number: "+234 905 932 3873",
    tags: ["Mexican", "Latin"],
    rateNumber: 4,
    category: "Restaurant",
    rate: 10,
    website: "https://www.getprospa.com/webstore/shoesbybecky",
  },
  {
    label: "Chipotle Mexican Grill",
    slug: "chipotle-mexican-grill-2",
    open: "Open",
    openTime: "7:00 AM - 8:00 PM",
    imgURL: "/assets/images/chipotle.png",
    location: "Abiola Okeke, Medina estate, Gbagada, Lagos",
    locationestate: "Gbagada, Lagos",
    number: "+234 905 932 3873",
    tags: ["Mexican", "Latin", "Grill"],
    rateNumber: 4,
    category: "Fast Food",
    rate: 20,
  },
  {
    label: "Boca Mexicana",
    slug: "boca-mexicana-2",
    open: "Open",
    openTime: "7:00 AM - 8:00 PM",
    imgURL: "/assets/images/pizza.png",
    location: "Suite 201, Block A2, 3 201 Simpson St, Lagos Island, Lagos",
    locationestate: "Gbagada, Lagos",
    number: "+234 905 932 3873",
    tags: ["Mexican", "Latin"],
    rateNumber: 4,
    category: "Restaurant",
    rate: 10,
    website: "https://www.getprospa.com/webstore/shoesbybecky",
  },
  {
    label: "Chipotle Mexican Grill",
    slug: "chipotle-mexican-grill-3",
    open: "Open",
    openTime: "7:00 AM - 8:00 PM",
    imgURL: "/assets/images/chipotle.png",
    location: "Abiola Okeke, Medina estate, Gbagada, Lagos",
    locationestate: "Gbagada, Lagos",
    number: "+234 905 932 3873",
    tags: ["Mexican", "Latin", "Grill"],
    rateNumber: 4,
    category: "Fast Food",
    rate: 20,
  },
  {
    label: "Boca Mexicana",
    slug: "boca-mexicana-3",
    open: "Open",
    openTime: "7:00 AM - 8:00 PM",
    imgURL: "/assets/images/pizza.png",
    location: "Suite 201, Block A2, 3 201 Simpson St, Lagos Island, Lagos",
    locationestate: "Gbagada, Lagos",
    number: "+234 905 932 3873",
    tags: ["Mexican", "Latin"],
    rateNumber: 4,
    category: "Restaurant",
    rate: 10,
    website: "https://www.getprospa.com/webstore/shoesbybecky",
  },
];
export const popularEventsData: LocationType[] = [
  {
    label: "Donating Blood Festival",
    slug: "donating-blood-festival",
    time: "12.12.22",
    imgURL: "/assets/images/cinema.png",
    location:
      "Corporate Headquarters, Plot 1551, Apo Resettlement Zone E, Federal Capital Teritory",
    number: "+234 905 932 3873",
    category: "Charity Event",
    serviceFees: "Free",
    btnName: "Register",
    eventFees: 2000,
  },
  {
    label: "Lagos Cinema Festival",
    slug: "lagos-cinema-festival",
    time: "22.12.22 - 23.12.22",
    imgURL: "/assets/images/virtual.png",
    location: "Magodo Phase 2, Kosofe",
    number: "+234 905 932 3873",
    category: "Entertainment",
    serviceFees: "From 6000",
    btnName: "Buy Ticket",
    eventFees: 0,
  },
  {
    label: "Lagos Beer and Grill Festival",
    slug: "lagos-beer-and-grill-festival",
    time: "19.12.22 - 26.12.22",
    imgURL: "/assets/images/virtual.png",
    location:
      "Corporate Headquarters, Plot 1551, Apo Resettlement Zone E, Federal Capital Teritory",
    number: "+234 905 932 3873",
    category: "Entertainment",
    serviceFees: "From 2000",
    btnName: "Buy Ticket",
    eventFees: 0,
  },
  {
    label: "Lagos Cinema Festival",
    slug: "lagos-cinema-festival",
    time: "22.12.22 - 23.12.22",
    imgURL: "/assets/images/virtual.png",
    location: "Magodo Phase 2, Kosofe",
    number: "+234 905 932 3873",
    category: "Entertainment",
    serviceFees: "From 6000",
    btnName: "Buy Ticket",
    eventFees: 0,
  },
  {
    label: "Lagos Beer and Grill Festival",
    slug: "lagos-beer-and-grill-festival-2",
    time: "19.12.22 - 26.12.22",
    imgURL: "/assets/images/virtual.png",
    location:
      "Corporate Headquarters, Plot 1551, Apo Resettlement Zone E, Federal Capital Teritory",
    number: "+234 905 932 3873",
    category: "Entertainment",
    serviceFees: "From 2000",
    btnName: "Buy Ticket",
    eventFees: 0,
  },
  {
    label: "Donating Blood Festival",
    slug: "donating-blood-festival-2",
    time: "12.12.22",
    imgURL: "/assets/images/cinema.png",
    location:
      "Corporate Headquarters, Plot 1551, Apo Resettlement Zone E, Federal Capital Teritory",
    number: "+234 905 932 3873",
    category: "Charity Event",
    serviceFees: "Free",
    btnName: "Register",
    eventFees: 2000,
  },
];
export const popularBusiness: LocationType[] = [
  {
    label: "Shoes by Becky",
    slug: "shoes-by-becky",
    openTime: "7:00 AM - 8:00 PM",
    imgURL: "/assets/images/shoe_business.png",
    location: "Abiola Okeke, Medina estate, Gbagada, Lagos",
    number: "+234 905 932 3873",
    category: "Shoes Store",
    open: "Open",
    website: "https://www.getprospa.com/webstore/shoesbybecky",
    tags: ["Shoe Store", "Cloth Store", "Clothes Customization"],
    rateNumber: 4,
    rate: 15,
  },
  {
    label: "Kokoma Shoe Co.",
    slug: "kokoma-shoe-co",
    imgURL: "/assets/images/toy_business.png",
    location: "Magodo Phase 2, Kosofe",
    number: "+234 905 932 3873",
    category: "Shoes Store",
    close: "Closed",
    rateNumber: 3,
    rate: 20,
    tags: ["Shoe Store", "Shoe Repair"],
  },
  {
    label: "LJT Shoes",
    slug: "ljt-shoes",
    openTime: "7:00 AM - 8:00 PM",
    imgURL: "/assets/images/shoe_business.png",
    location: "Idumota, 11 Ereko St, Lagos Island, Lagos, Нигерия",
    number: "+234 905 932 3873",
    category: "Shoes Store",
    open: "Open",
    rateNumber: 5,
    rate: 100,
    tags: ["Shoe Store", "Shoe Repair"],
  },
  {
    label: "Perfect Shoe Custom Shop",
    slug: "perfect-shoe-custom-shop",
    imgURL: "/assets/images/toy_business.png",
    location: "Idumota, 11 Ereko St, Lagos Island, Lagos, Нигерия",
    number: "+234 905 932 3873",
    category: "Laptops",
    open: "Open",
    rateNumber: 3,
    rate: 20,
    tags: ["Dell", "Samsung", "Macbook"],
    website: "www.allflesh.com",
  },
];



export const popularJobs: LocationType[] = [
  {
    imgURL: "/assets/images/agency.png",
    label: "Hotel Manger",
    slug: "hotel-manager",
    organization: "Agency Nest",
    jobtype: "Part-Time",
    serviceFees: "1,500 - 5,900",
    duration: "monthly",
    category: "template",
    company: "Lange & Grant ",
    location: "Walter Carrington Crescent, Victoria Island, Lagos",
    number: "+234 905 932 3873",
    btnName: "Apply Now",
    status: "active",
    tags: ["Shoe Store", "Cloth Store", "Clothes Customization"],

  },
  {
    imgURL: "/assets/images/ibis.png",
    label: "Hotel Manger",
    slug: "hotel-manager-2",
    organization: "Ibis Hotel",
    serviceFees: "1500",
    jobtype: "Part-Time",
    category: "tool",
    duration: "monthly",
    company: "Lange & Grant ",
    location: "Walter Carrington Crescent, Victoria Island, Lagos",
    number: "+234 905 932 3873",
    btnName: "Apply Now",
    status: "close",
  },
  {
    imgURL: "/assets/images/fxtn.png",
    label: "Sales Manager",
    slug: "sales-manager",
    category: "dapp'",
    organization: "Forex Time Nigeria",
    jobtype: "Full-Time",
    serviceFees: "2000",
    company: "Lange & Grant ",
    location: "Walter Carrington Crescent, Victoria Island, Lagos",
    number: "+234 905 932 3873",
    btnName: "Apply Now",
    status: "active",
  },
  {
    imgURL: "/assets/images/stanbic.png",
    label: "Financial Manager",
    slug: "financial-manager",
    organization: "Forex Time Nigeria",
    jobtype: "Full-Time",
    serviceFees: "500 - 2000",
    category: "dapp",
    company: "Lange & Grant ",
    location: "Walter Carrington Crescent, Victoria Island, Lagos",
    number: "+234 905 932 3873",
    btnName: "Apply Now",
    status: "active",
  },
];

export const popularProject: mapBackendStructure[] = [
  {
    projectName: "EcoTech Solutions",
    projectSummary:
      "Developing sustainable technology solutions for environmental conservation.",
    totalAmount: 1760,
    methodology: "Agile",
    appendices: ["Research Reports", "Prototype Designs"],
    expectedDeliverables: ["Prototype Model", "Feasibility Study"],
    milestones: ["Research Phase", "Prototype Development", "Testing Phase"],
    timeline: "6 months",
    team: [
      "Project Manager",
      "Software Developers",
      "Environmental Scientists",
    ],
    slug: "ecotech-solutions",
    projectDocumentation: "https://www.getprospa.com/webstore/shoesbybecky",
    securityMeasures: "Data encryption, access control",
    fairness: "Transparent selection process",
    technicalChallenges: [
      "Integration of IoT devices",
      "Optimizing energy efficiency",
    ],
    solution: "Smart waste management system",
    community: "Engagement with local environmental groups",
    scope: "Global impact",
    logoURI: "/assets/images/ibis.png",
    marketFit: "High demand for sustainable technology solutions",
    tokenomics: "No tokenomics applicable",
    id: 1,
    category: ["dapp"],
    status: "active",
  },

  {
    projectName: "HealthTech Innovations",
    projectSummary:
      "Creating cutting-edge technology solutions to improve healthcare accessibility.",
    minimumAmount: 500,
    totalAmount: 1750,
    methodology: "Scrum",
    appendices: ["Clinical Trials Data", "User Feedback"],
    expectedDeliverables: ["Mobile App Prototype", "Pilot Study Results"],
    milestones: ["Requirements Gathering", "Development Phase", "User Testing"],
    timeline: "9 months",
    team: ["Product Manager", "UX/UI Designers", "Medical Professionals"],
    slug: "healthTech-innovations",
    projectDocumentation: "https://www.getprospa.com/webstore/shoesbybecky",
    securityMeasures: "HIPAA compliance, encryption",
    fairness: "Equal opportunity for participation",
    technicalChallenges: [
      "Integration with legacy systems",
      "Ensuring data privacy",
    ],
    solution: "Telemedicine platform",
    community: "Engagement with healthcare providers",
    scope: "National rollout",
    logoURI: "/assets/images/agency.png",
    marketFit: "Growing demand for remote healthcare solutions",
    tokenomics: "No tokenomics applicable",
    id: 2,
    category: ["template", "dapp", ],
    status: "active",
  },
  {
    projectName: "EducationTech Hub",
    projectSummary:
      "Building an online platform to enhance educational resources and accessibility.",
    totalAmount: 2000,
    methodology: "Kanban",
    appendices: ["Educational Content", "User Surveys"],
    expectedDeliverables: ["Interactive Learning Modules", "Usage Analytics"],
    milestones: ["Content Creation", "Platform Development", "User Training"],
    timeline: "12 months",
    team: ["Project Lead", "Content Creators", "Software Engineers"],
    slug: "educationTech-hub",
    projectDocumentation: "https://www.getprospa.com/webstore/shoesbybecky",
    securityMeasures: "SSL encryption, user authentication",
    fairness: "Transparent content curation process",
    technicalChallenges: ["Scalability", "User interface optimization"],
    solution: "Online learning portal",
    community: "Engagement with educators and students",
    scope: "Global reach",
    logoURI: "/assets/images/fxtn.png",
    marketFit: "Growing demand for online education platforms",
    tokenomics: "No tokenomics applicable",
    id: 3,
    category: ["template"],
    status: "closed",
  },
  {
    projectName: "HealthTech Innovations",
    projectSummary:
      "Creating cutting-edge technology solutions to improve healthcare accessibility.",
    minimumAmount: 500,
    totalAmount: 1000,
    methodology: "Scrum",
    appendices: ["Clinical Trials Data", "User Feedback"],
    expectedDeliverables: ["Mobile App Prototype", "Pilot Study Results"],
    milestones: ["Requirements Gathering", "Development Phase", "User Testing"],
    timeline: "9 months",
    team: ["Product Manager", "UX/UI Designers", "Medical Professionals"],
    slug: "healthTech-innovations",
    projectDocumentation: "https://www.getprospa.com/webstore/shoesbybecky",
    securityMeasures: "HIPAA compliance, encryption",
    fairness: "Equal opportunity for participation",
    technicalChallenges: [
      "Integration with legacy systems",
      "Ensuring data privacy",
    ],
    solution: "Telemedicine platform",
    community: "Engagement with healthcare providers",
    scope: "National rollout",
    logoURI: "/assets/images/stanbic.png",
    marketFit: "Growing demand for remote healthcare solutions",
    tokenomics: "No tokenomics applicable",
    id: 4,
    category: ["tool"],
    status: "active",
  },
];




export const exploreNavigationLinks: FooterNavigationType[] = [

    { route: "#", label: "JavaScript" },
    { route: "#", label: "Python" },
    { route: "#", label: "Java" },
    { route: "#", label: "C++" },
    { route: "#", label: "C#" },
    { route: "#", label: "Ruby" },
    { route: "#", label: "Go" },
    { route: "#", label: "Rust" },
    { route: "#", label: "Swift" },
    { route: "#", label: "Kotlin" },
    { route: "#", label: "TypeScript" },
    { route: "#", label: "Solidity" }, // Ethereum smart contract language
    { route: "#", label: "Vyper" }, // Ethereum smart contract language
    { route: "#", label: "WebAssembly" }, // Smart contract language for Ethereum 2.0
    { route: "#", label: "Rust" }, // Can be used for smart contracts in Ethereum 2.0
    { route: "#", label: "SmartPy" }, // Smart contract language for Tezos
    { route: "#", label: "Michelson" }, // Smart contract language for Tezos
    { route: "#", label: "Cairo" }, // Smart contract language for StarkNet
    { route: "#", label: "Move" }, // Libra Blockchain language
    { route: "#", label: "Scala" }, // Language used in the Ethereum Virtual Machine (EVM)
    { route: "#", label: "Haskell" }, // Language used in the Cardano blockchain
   ];

